CREATE TABLE api_call_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(255),
    service VARCHAR(255),
    operation VARCHAR(255),
    request TEXT,
    response TEXT,
    status INT,
    cost_ms INT,
    created_at TIMESTAMP
);
